### PR TITLE
Replace Brittle #'s with <h5>'s

### PR DESCRIPTION
**Pull request by dgm34**
This should no longer break when our text editors trim the whitespace that used to follow the last #, thereby avoiding situations like this https://github.com/BBC-News/pr-templates/pull/4.  Example output pasted below, partly to demonstrate how this renders and partly to confuse you into thinking this is in fact a Responsive News PR....

## Coding checklist

- [ ] Jira ticket added
- [ ] Milestone added
- [ ] Pull request URL added to Jira ticket

<h5></h5>

- [ ] Up-to-date with develop (`git pull --rebase origin develop`)
- [ ] Tests exist for bug fixes and new features
- [ ] Sass compiles (`rm -rf tabloid/webapp/static/.sass-cache && grunt -gruntfile tabloid/webapp/static/Gruntfile.js sass:dist`)
- [ ] Code is standards-compliant (`rake code_sniffer && grunt -gruntfile tabloid/webapp/static/Gruntfile.js jshint`)
- [ ] PHPUnit tests pass (`rake test`)
- [ ] Jasmine tests pass (`grunt -gruntfile tabloid/webapp/static/Gruntfile.js test`)
- [ ] Images have been optimised (`grunt -gruntfile tabloid/webapp/static/Gruntfile.js imagemin`)
- [ ] Cukes pass (`ulimit -n 1024; bundle exec cucumber`)
- [ ] Salvo tests pass, e.g. (`WIDTH=1024 SITE=sandbox CONFIG=news.yaml rspec` or `WIDTH=1024 SITE=sandbox CONFIG=mundo.yaml rspec`)
- [ ] Layout checked with Ads on? (`?ads-debug&site=test`)
- [ ] Example URLs added to PR to help with testing

<h5></h5>

- [ ] UX reviewer thumbs up
- [ ] Accessibility thumbs up
- [ ] Code reviewer thumbs up
- [ ] Manual tester thumbs up

### CODE REVIEW

**Comment by dgm34** [comment]
## Coding checklist

- [ ] Jira ticket added
- [ ] Milestone added
- [ ] Pull request URL added to Jira ticket

######


- [ ] Up-to-date with develop (`git pull --rebase origin develop`)
- [ ] Tests exist for bug fixes and new features
- [ ] Sass compiles (`rm -rf tabloid/webapp/static/.sass-cache && grunt -gruntfile tabloid/webapp/static/Gruntfile.js sass:dist`)
- [ ] Code is standards-compliant (`rake code_sniffer && grunt -gruntfile tabloid/webapp/static/Gruntfile.js jshint`)
- [ ] PHPUnit tests pass (`rake test`)
- [ ] Jasmine tests pass (`grunt -gruntfile tabloid/webapp/static/Gruntfile.js test`)
- [ ] Images have been optimised (`grunt -gruntfile tabloid/webapp/static/Gruntfile.js imagemin`)
- [ ] Cukes pass (`ulimit -n 1024; bundle exec cucumber`)
- [ ] Salvo tests pass, e.g. (`WIDTH=1024 SITE=sandbox CONFIG=news.yaml rspec` or `WIDTH=1024 SITE=sandbox CONFIG=mundo.yaml rspec`)
- [ ] Layout checked with Ads on? (`?ads-debug&site=test`)
- [ ] Example URLs added to PR to help with testing

######


- [ ] UX reviewer thumbs up
- [ ] Accessibility thumbs up
- [ ] Code reviewer thumbs up
- [ ] Manual tester thumbs up

**Comment by dgm34** [comment]
ping @samfrench

**Comment by samfrench** [comment]
For newlines, should we use a `<br />` tag instead?

**Comment by dgm34** [comment]
## Coding checklist

- [ ] Jira ticket added
- [ ] Milestone added
- [ ] Pull request URL added to Jira ticket
<br />

- [ ] Up-to-date with develop (`git pull --rebase origin develop`)
- [ ] Tests exist for bug fixes and new features
- [ ] Sass compiles (`rm -rf tabloid/webapp/static/.sass-cache && grunt -gruntfile tabloid/webapp/static/Gruntfile.js sass:dist`)
- [ ] Code is standards-compliant (`rake code_sniffer && grunt -gruntfile tabloid/webapp/static/Gruntfile.js jshint`)
- [ ] PHPUnit tests pass (`rake test`)
- [ ] Jasmine tests pass (`grunt -gruntfile tabloid/webapp/static/Gruntfile.js test`)
- [ ] Images have been optimised (`grunt -gruntfile tabloid/webapp/static/Gruntfile.js imagemin`)
- [ ] Cukes pass (`ulimit -n 1024; bundle exec cucumber`)
- [ ] Salvo tests pass, e.g. (`WIDTH=1024 SITE=sandbox CONFIG=news.yaml rspec` or `WIDTH=1024 SITE=sandbox CONFIG=mundo.yaml rspec`)
- [ ] Yaml validates (`rake yamllint`)
- [ ] Layout checked with Ads on? (`?ads-debug&site=test`)
- [ ] Example URLs added to PR to help with testing

###### 

- [ ] UX reviewer thumbs up
- [ ] Accessibility thumbs up
- [ ] Code reviewer thumbs up
- [ ] Manual tester thumbs up

**Comment by dgm34** [comment]
Tried that but doesn't seem to work in the Markdown previewer...

**Comment by samfrench** [comment]
@dgm34, do you have an example of where you tried it out in the previewer?

**Comment by dgm34** [comment]
I tested it out here: https://github.com/BBC-News/pr-templates/edit/master/responsive-news.md using the preview changes functionality. I've also been pasting stuff in the comments section above to see how it renders (so apologies if you've been getting emailed about that...)

**Comment by samfrench** [comment]
Putting a double `<br /><br />` seems to work for me. If it doesn't work for you, then we can merge this (as this is an improvement on the space dividers).

**Pull request merged**
