### PR TITLE
Add link to Accessibility wiki page

### PR DESCRIPTION
**Pull request by coderkind**
Small addition to the checklist PR items so that developers are able to find information about accessibility and test easier/quicker.

### CODE REVIEW

**Comment by coderkind** [comment]
@dgm34 or @wildlyinaccurate; either of you able to review/merge this suggested small accessibility improvement to our checklist PR items? (cc @greenc05)

**Comment by dgm34** [comment]
Happy to do so. More info always good!

**Comment by greenc05** [comment]
Thanks @coderkind @dgm34

**Comment by wildlyinaccurate** [comment]
:+1: Nice!

**Comment by coderkind** [comment]
Thanks all :+1: :computer: :speech_balloon:

**Pull request merged**
