### PR TITLE
Restructure responsive-news checklist

### PR DESCRIPTION
**Pull request by wildlyinaccurate**
The current checklist has grown organically over the last year or so and as a result became a bit cluttered and unstructured. I feel like splitting it up in this way provides some much-needed structure, and also makes it clearer which items are optional, as well as which are run automatically on the push hook.

It looks like this:

## Coding checklist

- [ ] JIRA ticket added
- [ ] Milestone added
- [ ] Pull request URL added to JIRA ticket
- [ ] Example URLs added to help with testing
- [ ] Up-to-date with develop (`git pull --rebase origin develop`)

##### Unit tests and lints <small>(you can tick all of these if your latest commit has a green tick)</small>

- [ ] Sass compiles (`rm -r tabloid/webapp/static/stylesheets && grunt -gruntfile tabloid/webapp/static/Gruntfile.js sass:dist`)
- [ ] Code is standards-compliant (`rake code_sniffer && grunt -gruntfile tabloid/webapp/static/Gruntfile.js jshint`)
- [ ] PHPUnit tests pass (`rake test`)
- [ ] Jasmine tests pass (`grunt -gruntfile tabloid/webapp/static/Gruntfile.js test`)
- [ ] Yaml validates (`rake yamllint`)

##### Integration tests

- [ ] Cukes pass (`ulimit -n 1024; bundle exec cucumber`)
- [ ] Relevant Salvo tests pass, e.g. (`WIDTH=1024 SITE=sandbox CONFIG=<service>.yaml rspec`)

##### Misc.

- [ ] Tests exist for bug fixes and new features
- [ ] Images have been optimised (`grunt -gruntfile tabloid/webapp/static/Gruntfile.js imagemin`)
- [ ] Layout checked with Ads on (`?ads-debug&site=test`)

##### Review

- [ ] Code reviewer thumbs up
- [ ] Manual tester thumbs up
- [ ] UX reviewer thumbs up
- [ ] Accessibility thumbs up ([Testing for Accessibility](https://github.com/BBC-News/responsive-news/wiki/Testing-for-Accessibility))

### CODE REVIEW

**Comment by dgm34** [comment]
:+1:

**Comment by Guntrisoft** [comment]
:+1:  neat

**Comment by staylos92** [comment]
:cake:

**Comment by robsquires** [comment]
FWIW, I always liked the idea of:

**Integration tests**

- [ ] Smoke cukes pass (ulimit -n 1024; bundle exec cucumber --tags @smoketest)
- [ ] Relevant cukes pass (ulimit -n 1024; bundle exec cucumber _features/name.feature_)
- [ ] Relevant Salvo tests pass, e.g. (WIDTH=1024 SITE=sandbox CONFIG=<service>.yaml rspec)

**Comment by Matthew-Kirk** [comment]
@robsquires I'd be careful about that one, as it would encourage devs to only run the cukes they _think_ are affected, when one of the reasons to have them is to pick up regressions in somewhere unexpected. Granted, the ratio of false positives:real positives is not high, but it does happen from time to time.

**Comment by wildlyinaccurate** [comment]
@robsquires I would _really_ like to do that but I'm not sure whether we're confident enough that everything is sufficiently isolated. I've been caught out a few times in the past by my changes breaking seemingly unrelated cukes :(

**Comment by robsquires** [comment]
@Matthew-Kirk @wildlyinaccurate Yup totes. ... But I do really like the idea of those breakages, which in theory show signs of unnecessary/nasty coupling in the codebase, occurring in a public place. 

But yup, given the full suite is run overnight things might start getting a bit spicy + ultimately slow people down in the morning trying to track down what broke

**Comment by wildlyinaccurate** [comment]
Thanks for the feedback everyone. I'm gonna merge this as-is but please iterate on this in another PR if you have any ideas for improvement.

**Pull request merged**
