### PR TITLE
Add Back Whitespace

### PR DESCRIPTION
**Pull request by dgm34**
Sorry

### CODE REVIEW

**Comment by samfrench** [comment]
@dgm34, do you think we should update the readme in this repo, to say the whitespace is necessary? I know it caused issues previously, but the file you linked to yesterday looked fine in the browser.

**Comment by wildlyinaccurate** [comment]
It'd be nicer if we didn't use an empty header for spacing. `-------------` (`<hr>`) might be better?

**Comment by dgm34** [comment]
I mentioned it briefly to @wildlyinaccurate earlier. At the very least we should update the readme (I'll do that now). Is there not a better way of achieving the same result - e.g. adding a few more line breaks instead of a empty heading.

**Comment by dgm34** [comment]
Bah, @wildlyinaccurate beat me by a matter of seconds.

**Comment by dgm34** [comment]
https://github.com/BBC-News/pr-templates/pull/5 @samfrench ?

**Comment by samfrench** [comment]
@wildlyinaccurate, I like the suggestion of something else instead of empty headings. Does the text lose new line characters? If we had extra newlines, they get stripped out?

**Pull request merged**
